### ISSUE TITLE
Mangrove alerts widget does not appear on Safari browser

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#388]
A user reported the mangrove alerts widget does not appear when visiting globalmangrovewatch.org using the chrome browser. I've verified via zoom / screen sharing

**Comment by mluena** [comment]
Thanks for reporting it. I’ve just checked it on my phone and the widget seems fine for both safari and chrome, I’ll take a deeper look tomorrow from my laptop. Do you know which version was the user using?

**Comment by mluena** [comment]
Forget about the version, I cleaned my cache and it disappeared. The problem seems to come from data fetching, it throws an error and we don't show the widget when there is no data. Alicia is looking into this as is part of the same issue reported (alerts widget not updating when changing location).

**Comment by klongleywood** [comment]
Just noting that this is still an issue (I'm using Chrome)-- we'd like to highlight this feature during our GMW workshop this week so any updates would be appreciated fyi @dhakelila @lhilarides

**Comment by dhakelila** [comment]
Hi @klongleywood, we have identified the issue and we still need to fix it. We'll do it asap. 

Can you tell me the exact dates of the workshop? I have "early may" in my notes. 

Sorry for the inconvenience.

**Comment by mluena** [comment]
@klongleywood, @lhilarides which link will you use for the workshop? staging or production?

**Comment by mluena** [comment]
ok, I'll update production tomorrow morning with some of the bugs fixed. We are still working on the alerts. By any of the layers you mean for any widget?

**Comment by klongleywood** [comment]
Yes, she is not able to see any of the layers! Again, I'm not having the same problem.

**Comment by mluena** [comment]
I checked as well and everything seems fine in Safari. I'll check it tomorrow again as soon as I update production

**Comment by klongleywood** [comment]
@mluena and fyi @dhakelila -- Can you let me know when you update production? I just got more details on this from our training consultant. She has cleared her browser cache, updated her computer's operating system, tested on multiple computers (both macs) and multiple internet connections and still no success. I just did a screen share with her today to confirm it's not a user error. She also thinks that this has something to do with the cache since the speed and performance have declined gradually over the past week.  Can you look into this and if you can't ID the problem can you reach out with her directly? Her name is Annick (acros@hawaii.edu). She's trying to prepare for a training at our workshop next week, May 10th.
