### ISSUE TITLE
Change alerts showing different statistics for different users

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#401]
We were doing a demo of the change alerts on our workshop this morning, and we had users do a quick exercise to see how many change alerts were in Tanzania between June 2020 and September 2020. We ran into an issue because some users got 8 (including @lhilarides ), while others got 5 (including me). We don't think this is user error because we double checked the workflow live. Any idea why this might be happening?  FYI @dhakelila

**Comment by klongleywood** [comment]
![image](https://user-images.githubusercontent.com/54109064/168078406-bcde79e4-fcf2-471e-9666-ec291296ec7b.png)

**Comment by klongleywood** [comment]
I know -- it's super weird!! @lhilarides is getting 8 so maybe he can post a screenshot or you could work with him to identify the issue?

**Comment by lhilarides** [comment]
Doesn't matter what I do, I always get 8 alerts in this period
![image](https://user-images.githubusercontent.com/3919721/168240442-eb878f68-f4b7-41ab-95a4-4551d36164a1.png)

**Comment by lhilarides** [comment]
Now that I compare the two screenshots by Kate and me, I notice that some months are missing from the X-axis in the graphs. In Kate's version the month of June or July ("J") is missing, in my version the month of August is missing ("A"). 

I tried another time, and now the months interval seems to be incorrectly displayed:
![Uploading image.png…]()

**Comment by lhilarides** [comment]
Another one, probably related to this, that I ran in to this morning (hint: the start date for alerts is January 2020, there are no alerts in 2019):
[29f9bab](https://github.com/Vizzuality/mangrove-atlas/commit/29f9bab40e724faafffca84628576986fa2321a4)

**Comment by dhakelila** [comment]
@mluena did we solved the two issues referred to in this thread? 
I think you did for the second one but not sure for the first one.

**Comment by lhilarides** [comment]
Both issues still happening, but I think they are connected. If we fix 1, the other is also fixed. What I suspect is happening: the BigQuery sql in the Cloud Function creates a month field from a date value. This transforms a date (e.g. 2022-07-04) into the first day of the month (2022-07-01). This is then interpreted as a UTM time, which causes browsers with settings behind UTM time (anything across the Atlantic) to show it as a day earlier. So even if the timezone difference is just 1 hour, it's displayed as 2020-12-31-23:00 instead of 2021-01-01-00:00

Not sure if this is really what happens, but I can't think of anything else. To troubleshoot I've updated the SQL code in the Cloud Function. It now adds 1 day to the first of the month. Since the cache lasts 24 hours we'll have to wait for it to update and test.

**Comment by lhilarides** [comment]
Has been fixed by changing the cloud-function code
