### ISSUE TITLE
Restoration layer interactivity ready for your review

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#506]
Restoration layer interactivity is ready for you to review. 

Now, when a user hovers over one of the areas of the Restoration layer, the polygons get highlighted to indicate it can be clicked. 
Once user clicks, they get a pop-up with the information of that area. 

Although some improvements to the interactivity are still needed, it will be great if you could start reviewing the functionality and checking the numbers. 

https://www.loom.com/share/39b3878f8a084419a49fabac2b7418c1

**Comment by klongleywood** [comment]
@lhilarides @dhakelila similar to my comment on the Protection donut chart.  On the Restorable Mangrove Area part of the widget, shouldn't the number reported when you hover over the gray part of the donut represent the total non-restorable area, rather than the total mangrove area?

**Comment by dhakelila** [comment]
HI @klongleywood , I see it correctly. See attached screenshot. Does the issue persist for you? 

![Screenshot 2022-09-12 at 22 17 46](https://user-images.githubusercontent.com/6608294/189750629-190f9767-f10e-4903-8eea-0f97723addfa.png)

**Comment by dhakelila** [comment]
![Screenshot 2022-09-12 at 22 24 36](https://user-images.githubusercontent.com/6608294/189751907-e883d8d0-f323-469e-814d-c2eaa5aa2fb2.png)
Issue detected before with discrepancies on the data fixed as well.

**Comment by lhilarides** [comment]
One comment regarding the contrast of the blue & purple color ramp in the overview section and on the map: it is very difficult to see the difference between 40% and 80%, at least with my eyes on my screen. It looks like the map uses shades of transparency instead of blue. Either way, I think we should increase the contrast of the color ramp. See below comparison of the Ocean Wealth color ramp vs the current GMW as an illustration:

![image](https://user-images.githubusercontent.com/3919721/189945562-b551000c-ca06-4bbf-9932-556465e9da24.png)

**Comment by klongleywood** [comment]
@dhakelila the restoration widget is now in the right category and the donut number/percentage issue is fixed on my end.

**Comment by dhakelila** [comment]
@lhilarides about the colors on the layer, we realized it wasn't correctly generated and it only has one color. 
It should have the same colors than the widget.
Please, see screenshot and confirm whether that color ramp is ok. 

![Screenshot 2022-09-14 at 10 10 59](https://user-images.githubusercontent.com/6608294/190120517-a210ca68-1b22-4a69-bbee-e7273f4eb03b.png)

**Comment by dhakelila** [comment]
![Screenshot 2022-09-16 at 10 02 43](https://user-images.githubusercontent.com/6608294/190588440-ba561a61-30ff-476a-8d58-a942731d895b.png)

@lhilarides new color ramp proposed. This add more contrast while preserving the color schemas of other widgets

**Comment by dhakelila** [comment]
Colors look good!

**Comment by AngelArcones** [comment]
@lhilarides We've fixed the issue of the similar colour between patches on the Restoration Score layer (see screenshot).  

<img width="933" alt="Screenshot 2022-09-20 at 12 18 08" src="https://user-images.githubusercontent.com/57727579/191234299-3259a35c-5b05-4ec9-8a5a-52232b6047e0.png">
  
However, since the scores do not distribute equally between 0 and 100, the visualisation would not be taking full advantage of the color ramp. Most of the data fall between 50 and 80 aprox, with around ~650 patches with 0 values
  
![Screenshot 2022-09-20 at 10 36 38](https://user-images.githubusercontent.com/57727579/191234972-f25ec90b-ab30-4826-9845-0ce19e012734.png)
  
Our suggestion here would be to rearrange the scale to "stretch" it more along those relevant values between 35/40 and 100. An example of slightly different intervals distribution would look like this test:

<img width="508" alt="Screenshot 2022-09-20 at 12 17 15" src="https://user-images.githubusercontent.com/57727579/191235840-f676a2cd-c234-4338-81d1-6337957026d6.png">

**Comment by lhilarides** [comment]
I'd be fine stretching the contract a bit, looks good!

I did find one small CSS issue with the popup in this layer, see below:
![image](https://user-images.githubusercontent.com/3919721/191350562-cbe72cea-ebb7-4c9f-abca-3cbd64267f01.png)

**Comment by klongleywood** [comment]
@dhakelila and fyi @lhilarides -- the Mangrove Restoration dataset is on production and it should not be. We're already getting inquiries about it. Please take it down as soon as you can!

**Comment by mluena** [comment]
@klongleywood done! you will be able to see the changes in a few minutes

**Comment by klongleywood** [comment]
@mluena thanks!
