### ISSUE TITLE
Carbon Market Potential widget: missing unit

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#673]
Tiny issue: please add the unit in the Carbon Market Potential widget:

![image](https://user-images.githubusercontent.com/3919721/212959283-38364bd4-7ee0-4f9e-b89a-7d8840c145e8.png)

**Comment by dhakelila** [comment]
Ready for your revision in staging
<img width="508" alt="Screenshot 2023-01-23 at 09 46 14" src="https://user-images.githubusercontent.com/6608294/213998017-79b4a240-74d3-46d0-aa29-d2e714455991.png">

**Comment by mluena** [comment]
We are reviewing the number's formatting across the platform to improve consistency. currently, we are showing 2 decimals for all widgets, in case those two decimals are 0 how do you prefer us to proceed? leave two decimals -> .00. Remove them completely or leave just one? @lhilarides , @klongleywood

**Comment by klongleywood** [comment]
If the number of decimals has to be consistent across the entire platform, I would suggest removing all decimal places.  Generally, I would prefer to have the number of decimal places decided on a widget-by-widget basis since some data sources have more precision associated than others, but as a default I think no decimals is ok.

**Comment by dhakelila** [comment]
I see, Kate. That would also be an option. If we start a new phase, we are already planning to do some review of the whole project to gain consistency and robustness, and that can be something to add. 

So for now, let's keep things as they are.
