### ISSUE TITLE
Data applicability

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#711]
[insert design when ready]

**Comment by larranz-vizz** [comment]
Hello, @lhilarides and @klongleywood:

I have made a [design](https://www.figma.com/file/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?node-id=1887-12999&t=srY1G1YxuWUKpPAa-4) based on your input last week. I tried with the visual scale you suggested, but it looked complex and crowded because there are other graphics in the widget. Just the text seems more clear.

Let us know what you think.

Thanks!

**Comment by lhilarides** [comment]
Hi @larranz-vizz , I agree. It's basic, but it's very clear and I think serves the purpose well 👍

**Comment by klongleywood** [comment]
@dhakelila and fyi @lhilarides 
I added this information to column K. In terms of the sentences, I think we could keep it pretty simple, just saying, as in the mock-up design, Data applicability, and then the following categories.  The one thing we might want to add in the info button is whether there is a specific zoom level beyond which we recommend using the dataset without verification from local sources? Maybe we can discuss with the rest of the team on Friday

- Global scale only
- National scale only
- Global and national scales
- Global, national, and sub-national scales
- National and sub-national scales
