### ISSUE TITLE
Map settings section

### ISSUE THREAD

**Issue by larranz-vizz** [Vizzuality/mangrove-atlas#745]
Hello @lhilarides and @klongleywood,

I have the final [design](https://www.figma.com/proto/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?page-id=0%3A1&type=design&node-id=1787-7188&viewport=1576%2C-17777%2C1&scaling=min-zoom&starting-point-node-id=1787%3A7188&show-proto-sidebar=1). As we discussed, we are adding a new section in the sidebar to access the settings. You can see the basemaps settings and the different contextual layers from there.

Let me know what you think.

Thanks!

**Comment by klongleywood** [comment]
Hi @larranz-vizz, 

We just took a look at this on our team call and had the following comments. 

Overall, the placement of the icon for this is fine but we're wondering if we can call this Basemaps rather than Settings? 

The team also wondered about the ease of toggling the high res basemap on and off to be able to quickly compare against the other extent/data layers. Is there a way that a user would be able to do this without having to go back into the Settings?

Finally, can you confirm that we'd only be able to see one basemap from the high res data at a time (e.g., one timestep).

**Comment by larranz-vizz** [comment]
Hello @lhilarides and @klongleywood,

I have an update related to this design. As Clara explained, you have a use case that requires you to see the satellite settings quickly when analyzing alerts.

I propose having them next to the shortcut we designed to change the map quickly. So when the map is activated, users also manage its settings from the alerts widget. [You can take a look here](https://www.figma.com/file/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?type=design&node-id=2931-28175&t=douQ3SVbS0kELE5T-4).

This way, we avoid the legend on the map being so large that it obscures the map itself.

Kate, regarding your last comments, I think you already discussed them with Clara. Am I right?

Thank you!

**Comment by lhilarides** [comment]
Looks good as far as I'm concerned @larranz-vizz

**Comment by dhakelila** [comment]
@lhilarides , @klongleywood , now that we are starting the implementation of the new satelite basemap, and as discussed, we need you to provide the API key to access the planet APi where we'll grab the data. 

In case you haven't done it yet, you need to join one of the programs to gain access to it. 
https://www.planet.com/get-started/#programs

**Comment by dhakelila** [comment]
Hi @lhilarides , please, use this to share the API-key with us: https://onetimesecret.com/
